/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard.timeline'
import { Route as DashboardRemindersRouteImport } from './routes/dashboard.reminders'
import { Route as DashboardMedicalReportsRouteImport } from './routes/dashboard.medical-reports'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardDiaryRouteImport } from './routes/dashboard.diary'
import { Route as DashboardAnalyzeRouteImport } from './routes/dashboard.analyze'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard.reports.index'
import { Route as DashboardReportsReportIdRouteImport } from './routes/dashboard.reports.$reportId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicalReportsRoute = DashboardMedicalReportsRouteImport.update({
  id: '/medical-reports',
  path: '/medical-reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiaryRoute = DashboardDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyzeRoute = DashboardAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsReportIdRoute =
  DashboardReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analyze': typeof DashboardAnalyzeRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/medical-reports': typeof DashboardMedicalReportsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analyze': typeof DashboardAnalyzeRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/medical-reports': typeof DashboardMedicalReportsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analyze': typeof DashboardAnalyzeRoute
  '/dashboard/diary': typeof DashboardDiaryRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/medical-reports': typeof DashboardMedicalReportsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/analyze'
    | '/dashboard/diary'
    | '/dashboard/insights'
    | '/dashboard/medical-reports'
    | '/dashboard/reminders'
    | '/dashboard/timeline'
    | '/dashboard/'
    | '/dashboard/reports/$reportId'
    | '/dashboard/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/analyze'
    | '/dashboard/diary'
    | '/dashboard/insights'
    | '/dashboard/medical-reports'
    | '/dashboard/reminders'
    | '/dashboard/timeline'
    | '/dashboard'
    | '/dashboard/reports/$reportId'
    | '/dashboard/reports'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/analyze'
    | '/dashboard/diary'
    | '/dashboard/insights'
    | '/dashboard/medical-reports'
    | '/dashboard/reminders'
    | '/dashboard/timeline'
    | '/dashboard/'
    | '/dashboard/reports/$reportId'
    | '/dashboard/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reminders': {
      id: '/dashboard/reminders'
      path: '/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medical-reports': {
      id: '/dashboard/medical-reports'
      path: '/medical-reports'
      fullPath: '/dashboard/medical-reports'
      preLoaderRoute: typeof DashboardMedicalReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/diary': {
      id: '/dashboard/diary'
      path: '/diary'
      fullPath: '/dashboard/diary'
      preLoaderRoute: typeof DashboardDiaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analyze': {
      id: '/dashboard/analyze'
      path: '/analyze'
      fullPath: '/dashboard/analyze'
      preLoaderRoute: typeof DashboardAnalyzeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$reportId': {
      id: '/dashboard/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/dashboard/reports/$reportId'
      preLoaderRoute: typeof DashboardReportsReportIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyzeRoute: typeof DashboardAnalyzeRoute
  DashboardDiaryRoute: typeof DashboardDiaryRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardMedicalReportsRoute: typeof DashboardMedicalReportsRoute
  DashboardRemindersRoute: typeof DashboardRemindersRoute
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReportsReportIdRoute: typeof DashboardReportsReportIdRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyzeRoute: DashboardAnalyzeRoute,
  DashboardDiaryRoute: DashboardDiaryRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardMedicalReportsRoute: DashboardMedicalReportsRoute,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReportsReportIdRoute: DashboardReportsReportIdRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
